document.write("Struktura fakulty:<br>"
+"<br>"
          +"Katedra ekonometrie (K-101)<br>"
              +"Vedoucí katedry: prof. RNDr. Zdeněk Zemánek, CSc.​ <br>"
         + "Katedra ekonomie (K-102)<br>"
             +" Vedoucí katedry: prof. PhDr. Miroslav Krč, CSc. <br> "
         +" Katedra logistiky (K-104)<br>"
              +"Vedoucí katedry: plk. gšt. Ing. Zbyšek KORECKI, Ph.D.<br> "
         + "Katedra ochrany obyvatelstva (K-106)<br>" 
              +"Vedoucí katedry: brig. gen. v zál. prof. Ing. Rudolf URBAN, CSc., dr. h. c.<br>"
        + " Katedra řízení palebné podpory (K-107)<br>"
             + "Vedoucí katedry: brigádní generál prof. Ing. Bohuslav PŘIKRYL, Ph.D.<br>"
         + "Katedra řízení zabezpečení boje (K-108)<br>"
             + "Vedoucí katedry: plk. Ing. Lubomír Kroupa, CSc.<br>"
        + " Katedra řízení lidských zdrojů (K-109)  <br>"
             + "Vedoucí katedry: Doc. RNDr. Ladislav HALBERŠTÁT, CSc. <br>"
          +"Katedra vojenského managementu a taktiky (K-110)<br>"
              +"Vedoucí katedry: plk. Ing. Miroslav Mašlej, Ph.D. <br>"
          +"Katedra celoživotního vzdělávání (K-111)<br>"
            + " Vedoucí katedry: Ing. Pavel ZŮNA, Ph.D., MSS.<br>");