

document.write("Struktura fakulty:<br>"
+"<br>"
        +"Katedra zbraní a munice (K-201)<br>"
        +"Vedoucí katedry: plk. prof. Ing. Martin Macko, CSc.​<br>"
        +"Katedra bojových a speciálních vozidel (K-202)<br>"
        +"Vedoucí katedry: plk. doc. Ing. Štefan ČORŇÁK, Dr.<br>"
        +"Katedra ženijních technologií (K-203)<br>"
        +"Vedoucí katedry: plk. doc. Ing. Pavel Maňas, Ph.D.<br>"
        +"Katedra letecké a raketové techniky (K-204)<br>"
        +"Vedoucí katedry: doc. Ing. Miloslav Petrásek, CSc.<br>"
        +"Katedra letectva (K-205)<br>"
        +"Vedoucí katedry: plk. gšt. Ing. Miloslav Bauer, Ph.D.<br>"
        +"Katedra leteckých elektrotechnických systémů (K-206)<br>"
        +"Vedoucí katedry: plk. doc. Ing. Miloš Andrle, CSc.<br>"
        +"Katedra radiolokace (K-207)<br>"
        +"Vedoucí katedry: plk. doc. Ing. Libor DRAŽAN, CSc.<br>"
        +"Katedra systémů PVO (K-208)<br>"
        +"Vedoucí katedry: plk. doc. Dr. Ing. Alexandr Štefek<br>"
        +"Katedra komunikačních a informačních systémů (K-209)<br>"
        +"Vedoucí katedry: plk. doc. Ing. Vlastimil Malý, CSc.<br>"
        +"Katedra vojenské geografie a meteorologie (K-210)<br>"
        +"Vedoucí katedry: plk. Ing. Vladimír Kovařík, Ph.D. MSc.<br>"
        +"Katedra matematiky a fyziky (K-215)<br>"
        +"Vedoucí katedry: prof. RNDr. Jan KOHOUT, CSc.<br>"
        +"Katedra strojírenství (K-216)<br>"
        +"Vedoucí katedry: plk. doc. Ing. Milan Chalupa, CSc.<br>"
        +"Katedra elektrotechniky (K-217)<br>"
        +"Vedoucí katedry: prof. Ing. Čestmír Vlček, CSc.<br>");